name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step 1: Install npm dependencies
      - name: Install Dependencies
        run: npm install

      # Step 2: Build your application
      - name: Build
        run: npm run build

      # Step 3: Start your application (if needed)
      # - name: Start Application
      #   run: npm start

      # Step 4: Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
